export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAILED = "AUTH_FAILED";
export const REGISTER_FAILED = "REGISTER_FAILED";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const LOGIN_FAILED = "LOGIN_FAILED";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const AUTH_LOGOUT = "AUTH_LOGOUT";
// export const CHECK_USER_CREDENTIALS_DB = "CHECK_USER_CREDENTIALS_DB";
// export const REGISTER_USER_WITH_CREDENTIALS_DB =
//   "REGISTER_USER_WITH_CREDENTIALS_DB";

export const INIT_AUTH_DATA_FROM_LOCAL_STORAGE =
  "INIT_AUTH_DATA_FROM_LOCAL_STORAGE";
